### ISSUE TITLE
Undefined variable $theme_location

### ISSUE THREAD

**Issue by studiovanzwet** [roladn/wordpress-bootstrap-menu#1]
Hi Roland,

Thank you making this repository. I got an error: "Undefined variable: theme_location in functions.php"
$theme_location

My functions.php file:
[functions.zip](https://github.com/roladn/wordpress-bootstrap-menu/files/1571079/functions.zip)

Section in index.php:
```
<ul class="nav navbar-nav menu clearfix" id="menu">
   <?php if (function_exists(TopMenu())) TopMenu(); ?>
</ul>
```

My menu settings:
![schermafbeelding 2017-12-19 om 10 52 15](https://user-images.githubusercontent.com/6659380/34151191-d21aa324-e4aa-11e7-98ca-a44f615d567d.png)
![schermafbeelding 2017-12-19 om 10 52 30](https://user-images.githubusercontent.com/6659380/34151192-d23befc0-e4aa-11e7-9016-c1f0f3b5937b.png)

Greets, Dennis.

**Comment by rolandalla** [comment]
![image](https://user-images.githubusercontent.com/5981015/34152347-9427ec9e-e4ae-11e7-9c4c-f83c9a1e443c.png)
Please change the registered primary menu slug to ps. 'primary' ,
The menu slug menu-1 is gnerated default on the first menu item.
Regards

**Comment by studiovanzwet** [comment]
That worked, thank you. Got a error: "Notice: Undefined variable: bool in functions.php on line 42" because I did not have a submenu. Had to declare the variable:  
![schermafbeelding 2017-12-19 om 11 41 39](https://user-images.githubusercontent.com/6659380/34153285-d1f1dc9e-e4b1-11e7-825c-f33b93abf4df.png)

Thank you again, I've got it working now.

Regards, Dennis

**Comment by rolandalla** [comment]
Hi Dennis,
Happy to see you solved it .
I forget to declare the variables 👍 
Regards

**Comment by studiovanzwet** [comment]
ps. you have 1 equal sign (=) to much on line 5. $bool==false had to be $bool=false
